/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type NoteTransformer from '#transformers/note_transformer'

export namespace Data {
  export type Note = InferData<NoteTransformer>
  export namespace Note {
    export type Variants = InferVariants<NoteTransformer>
  }
}
